### ISSUE TITLE
zh-Hant text in the filter ribbon too cramped

### ISSUE THREAD

**Issue by planetarian** [planetarian/TsunKitTranslations#6]
Will need to apply some text styling specific to zh-Hant to ensure characters are displayed at a sufficient size to be readable in the ribbon. Current font size is too small. Additional layout adjustments may be necessary.

**Comment by soloblast** [comment]
Rarity - 稀有度
Friend Fleets - 友軍艦隊
Node - 點
Edge - 邊
AD - 航空劣勢
AP - 航空均勢
AS - 航空優勢
AS+ - 制空權確保
LoS/Radar - 索敵/電探
Cn1/2/3/4 is apparently 分歧點係數 but should be self-explanatory?
Enemies - could go with 深海配置 but that's more like Abyssal Configurations/Formations (yeah I stole the term from KCWiki)

**Comment by sinsinpub** [comment]
I guess font-size is not an issue although really small, because chromium-based browsers get `Minimum font size` setting, and default value for CJK versions is 12px, instead of 11px in western.
without any custom style, it looks like this if `Minimum font size` is 12
![image](https://user-images.githubusercontent.com/160240/116813727-d193ef80-ab87-11eb-9f21-a8125640273d.png)

ofc, apply `.ribbon-section-content` custom css to set `smaller` -> `small` (13px), looks fine too
![image](https://user-images.githubusercontent.com/160240/116813879-aeb60b00-ab88-11eb-9024-90ba59fec981.png)

**Comment by planetarian** [comment]
Setting font size to `small` seems fine to me. Added in 4288c90
